eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator

.github/workflows/ci.yml

Add following workflow file: ci.yml

releng: Add github workflow for continuous integration

---

BUILDING.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
NOTICE.md
README.md
SECURITY.md
doc/org.eclipse.tracecompass.incubator.scripting.doc.user/doc/User-Guide.mediawiki
trace-server/README.md

- Add required legal document
- CODE_OF_CONTUCT.md
- LICENSE
- NOTICE.md
- SECURITY.md
- Update doc after migration to GitHub
- Update
- README.md
- trace-server/README.md
- Add
- BUILDING.md
- CONTRIBUTING.md

doc: add and update project documation 

---

tracetypes/org.eclipse.tracecompass.incubator.tracecompass.core/xml_analyses/GroupedTasks.xml
tracetypes/org.eclipse.tracecompass.incubator.traceevent.core/xml_analysis/GroupedTasksTraceEvent.xml

This fixes warnings about the nashorn engine missing.

xml-analysis: remove reference to nashorn

---

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
rcp/org.eclipse.tracecompass.incubator.rcp.product/tracing.incubator.product
rcp/org.eclipse.tracecompass.incubator.rcp/feature.xml

releng: Upgrade target to dependencies of 2024-06 (Eclipse 4.32) release

---

analyses/org.eclipse.tracecompass.incubator.executioncomparison.core/META-INF/MANIFEST.MF
analyses/org.eclipse.tracecompass.incubator.executioncomparison/feature.xml
rcp/org.eclipse.tracecompass.incubator.rcp.product/tracing.incubator.product

This PR adds the execution-comparison feature to the incubator's RCP.
Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>

execution-comparison: add to RCP

---

analyses/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkLogicalCoreAnalysisModule.java

dpdk: Remove unused imports warnings dpdk.core plug-in

---

tracetypes/org.eclipse.tracecompass.incubator.jifa.core/src/org/eclipse/tracecompass/incubator/internal/jifa/core/gclog/xmlanalysis/gc_analysis.xml

Change-Id: I9c2b9fcb09c9ca57a95971435119f1b92d0fa91f

fix gc log analysis to only be present on gc logs

---

tracetypes/org.eclipse.tracecompass.incubator.uftrace.core/src/org/eclipse/tracecompass/incubator/internal/uftrace/core/trace/Uftrace.java

The symbol provider now returns null when it cannot resolve rather than returning a string address. This allows chaining of symbol resolvers.
It is also made into a static class so that it is easier to debug.
Change-Id: Ifdfb7877f623c5e96feae0138308544ad4c0ab81

uftrace: fix symbol provider to not fix false negatives

---

tracetypes/org.eclipse.tracecompass.incubator.traceevent.core/src/org/eclipse/tracecompass/incubator/internal/traceevent/core/trace/TraceEventTrace.java

Give a full message instead of "Not a trace event trace" Also replace method reference instead of lambda.
Change-Id: I35b6d68b9ba66422a34a955ed9036cc01ff48acd

trace-event: improve error message

---

analyses/org.eclipse.tracecompass.incubator.rocm.core/src/org/eclipse/tracecompass/incubator/rocm/core/exatracer/trace/RocmExatracerTrace.java

The precedent validation would identify every lttng-ust traces as a rocm exatracer trace. This patch corrects that by looking if the trace has any events from a hip or hsa provider.

rocm: validate only ust traces containing rocm events

---

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product

releng: Upgrade target to dependencies of 2024-09 (Eclipse 4.33) release

---

tracetypes/org.eclipse.tracecompass.incubator.jifa.core/plugin.properties
tracetypes/org.eclipse.tracecompass.incubator.jifa.core/plugin.xml

Allows the user to view heap sizes
Change-Id: I86616c05505c6341311864ce5c12b883434dcdad

jifa: Add memory usage analysis

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/TraceManagerServiceTest.java

Added unit test case to make sure that server replies correctly.
Test was extracted from #89.

server: Test fetch trace if trace is not available on server

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Configuration.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/ConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/OutputConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ConfigurationManagerService.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java

Cherry picks of recent commits in master branch

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/IdentifierServiceTest.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ServerInfoResponse.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/IdentifierService.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ServerInfoResponseImpl.java

- Update TSP version to 0.2.0 due recent updates
- Show TSP version supported by server in IdentifierService

Update TSP version and show it IdentifierService

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/IdentifierServiceTest.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ServerInfoResponse.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/IdentifierService.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ServerInfoResponseImpl.java

Cherry picks of recent changes in master branch

---

analyses/org.eclipse.tracecompass.incubator.inandout.core/build.properties
analyses/org.eclipse.tracecompass.incubator.inandout.core/plugin.xml
analyses/org.eclipse.tracecompass.incubator.inandout.core/schema/in-and-out-analysis.json
analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutAnalysisModule.java
analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java
analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/SegmentSpecifierConfiguration.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderServiceTest.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product

Cherry-picks of recent changes in master branch

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java

The bookmarks file can be used to store and retrieve markers associated with an experiment using platform APIs.
It can later be obtained for an opened experiment with: TmfTraceManager.getInstance().getTraceEditorFile(experiment)

server: Create bookmarks file for experiments

---

tracetypes/org.eclipse.tracecompass.incubator.uftrace.core/META-INF/MANIFEST.MF
tracetypes/org.eclipse.tracecompass.incubator.uftrace.core/src/org/eclipse/tracecompass/incubator/internal/uftrace/core/trace/Uftrace.java

Use CDT's cppFilt to demange c++ names if available.

uftrace: demangle c++ names

---

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target

releng: Upgrade target to dependencies of 2024-12 (Eclipse 4.34) release

---

analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/META-INF/MANIFEST.MF
analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/src/org/eclipse/tracecompass/incubator/inandout/core/tests/analysis/InAndOutDataProviderFactoryTest.java

Add InAndOutDataProviderFactory JUnit Tests

---

common/org.eclipse.tracecompass.incubator.target/pom.xml
common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-e4.34.target

Add tracecompass-incubator-e4.34.target for 2024-12 builds.
`mvn clean install -Dtarget-platform=tracecompass-incubator-e4.34`
N/A

releng: Add tracecompass-incubator-e4.34.target for 2024-12 builds

---

common/org.eclipse.tracecompass.incubator.releng-site/category.xml
rcp/org.eclipse.tracecompass.incubator.rcp.product/tracing.incubator.product
tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/META-INF/MANIFEST.MF
tracetypes/org.eclipse.tracecompass.incubator.dpdk/feature.xml

This patch creates a new feature that consolidates the previously developed DPDK analyses.

Integrate DPDK analyses into a new feature

---

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-e4.34.target
common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target

Upgrade to trace-event-logger 0.4.0
Application uses the new version and logged timestamps are relative to epoch.
N/A

releng: Upgrade to trace-event-logger 0.4.0

---

analyses/org.eclipse.tracecompass.incubator.inandout.core/schema/in-and-out-analysis.json

Fix typo in InAndOut configuration schema: `descritpion` -> `description`
Successful JUnit tests.
None

inandout: Fix typo in InAndOut configuration schema

---

analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/src/org/eclipse/tracecompass/incubator/inandout/core/tests/analysis/InAndOutDataProviderFactoryTest.java
analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java

inandout: do not share configuration table

---

.github/workflows/ci.yml
common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
pom.xml
trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product

Trace Compass 10.3.0
Change JDK version to Java 21 in main pom.xml.
Change JDK version to Java 21 in ci.yml github workflow.

releng: Upgrade target to dependencies of 2025-03 (Eclipse 4.35) release

---

common/org.eclipse.tracecompass.incubator.releng-site/category.xml

Add o.e.tc.i.trace.server.jersey.rest.core on main update site. With this users can get this bundle from the main incubator update site. Also add source bundles on in incubator update site. With this users can read source code without having to clone the incubator source repository.
Build manually and check that all source bundles (incl.  `org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core` and `org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.source`) are on the locally built update site:
``` bash
cd common/org.eclipse.tracecompass.incubator.releng-site/target/repository/plugins
ls | grep rest.core
ls | grep source
```

Add o.e.tc.i.trace.server.jersey.rest.core and all source bundles to the update site

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java

Use new methods XmlDataProviderManager.getXmlDataProviderDescriptors() and XmlDataProviderManager.getXmlProvider() and delete the local methods.
Get all data providers or get a data provider configured by XML.
N/A

server: Use new API from XmlDataProviderManager

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java

swagger/server: Update TSP version to 0.4.0
Run server and query identifier endpoint.
```bash
./tsp_cli_client --get-identifier
```

swagger/server: Update TSP version to 0.4.0

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Annotation.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/AnnotationsQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ArrowsQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Element.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ExperimentQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/LinesQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OptionalQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputConfigurationQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/RequestedFilterQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/RequestedQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/SeriesModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ServerInfoResponse.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeGraphArrow.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeGraphRowModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeGraphState.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeRange.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TooltipQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TraceQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeColumnHeader.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeDataModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeEntryModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/XYModel.java

swagger: replace deprecated required field with requiredMode. This removes all related deprecated warnings.
Generate yaml file as described in step 4 of: https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api. The specification should have the same content in respect to required fields.

swagger: replace deprecated required field with requiredMode

---

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ExperimentQueryParameters.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/SeriesModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeGraphRowModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeDataModel.java
trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/XYModel.java

Apply workaround suggested in ticket:
https://github.com/swagger-api/swagger-core/issues/4341
Generate openapi.yaml file and verify that required statements are there again for all arrays.
N/A

swagger: fix missing required definitions for array

---

rcp/org.eclipse.tracecompass.incubator.rcp/feature.xml

rcp: Remove versions from certain dependencies in feature.xml.
Let the target definition decide on the actual version to use, which allows for building the RCP feature for different targets using the same feature.xml.
Successful CI for master target definition. To build for 2024-12 target to the following steps:
```bash
cd rcp/org.eclipse.tracecompass.incubator.rcp.product/
cp legacy/tracing.incubator.product .
mvn clean install -DskipTests=true
```
None

rcp: Remove versions from certain dependencies in feature.xml
