eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator

.github/workflows/ci.yml
Add following workflow file: ci.yml for 2021-06 branch. It uses different maven command-line parameters and copies the legacy product files for RCP and Trace Server before running the maven build.
=> releng: Add github workflow for continuous integration (2021-06 branch)

tracetypes/org.eclipse.tracecompass.incubator.ftrace.core.tests/src/org/eclipse/tracecompass/incubator/ftrace/core/tests/binary/buffer/BinaryFTraceByteBufferTest.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/header/BinaryFTraceHeaderInfo.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/iterator/BinaryFTraceCPUPageIterator.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/iterator/BinaryFTraceCPUSectionIterator.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/iterator/BinaryFTraceIterator.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/iterator/BinaryFTraceIteratorHelper.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/iterator/BinaryFTraceReader.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/parser/AbstractBinaryFTraceFileParser.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/parser/BinaryFTraceByteBuffer.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/parser/BinaryFTraceFileMapping.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/binary/parser/BinaryFTraceFileParser.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/strategies/BinaryFTraceV6Strategy.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/strategies/IBinaryFTraceStrategy.java, tracetypes/org.eclipse.tracecompass.incubator.ftrace.core/src/org/eclipse/tracecompass/incubator/internal/ftrace/core/trace/BinaryFTrace.java
* mmap the whole file for faster parsing
* re-use the same mapping to read events
on my (oldish) laptop with ubuntu 24.04 the file is parsed an order of magnitude faster
on a recent windows laptop I measured two orders of magnitude faster
=> ftrace: improve binary parser speed by optimizing I/O

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
Use older version of org.mozilla.javascript for compatibility with incubator EASE Scripting feature.
=> releng: Downgrade org.mozilla.rhino to org.mozilla.javascript

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Experiment.java
Don't rely on the order of traces array in experiment and trace UUIDs stored in ExperimentManagerService to create TSP Experiment model. Instead use the trace resources to create the TSP Trace model return in the TSP Experiment Model.
Fixes #51
[Fixed] potential trace UUID mismatch when creating experiment model
=> server: Fix potential trace UUID mismatch when creating experiment model

analyses/org.eclipse.tracecompass.incubator.rocm.core/plugin.xml
This analysis was removed from the extensions as the trace type changed. It is needed again so this commit adds it again to the plugin extensions.
=> rocm: restore previous ROCm analysis

trace-server/README.md
Currently the reference points to itself - it seems to make more sense to point to the root BUILDING.md file.
=> [server][readme] fix reference to general build instructions

rcp/org.eclipse.tracecompass.incubator.rcp.product/legacy/tracing.incubator.product
`org.eclipse.tracecompass.incubator.gpu` and `org.eclipse.tracecompass.incubator.executioncomparision` feature were missing and this PR adds these features to the legacy RCP product definition. Even if the legacy product definition is only used in branch 2021-06, it needs to be consistent in master branch as well. This will future cherry-picks to 2021-06 branch easier.
=> Add missing features to legacy rcp product definition

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/TraceModelStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Trace.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Experiment.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Trace.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TraceSerializer.java
[server] Add trace properties to the Trace instance
The purpose of this commit is to get the trace properties using tsp. The "properties" attribute will be in the trace instance, and it will be filled if the opened trace implements ITmfPropertiesProviders.
Example:
{
"name": "string",
"path": "string",
"nbEvents": 0,
"start": 0,
"indexingStatus": "RUNNING",
"end": 0,
"properties":
{
"hostname": "qemu1",
"clock_offset": "1450192743562703624"
},
"UUID": "f50af7e0-0dd5-4361-ab96-2e04f7bc7e30"
}
[Added] "properties" field in the returned Trace instance
[Added] a separate trace instrance will be created when "/traces" is queried
[Changed] /experiment endpoint will use Trace.from(ITmfTrace) to get more info of the trace
=> [server] Add trace properties to the Trace instance

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/TableColumnHeader.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/TreeModelWrapper.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TreeColumnHeaderSerializer.java
When requesting the table columns, the server will now return the type of each column. The types are derived from `DataType` enum, such as `STRING`, `NUMBER`, `TIMESTAMP`, `DURATION`, etc.
This feature supports both `IEventAspect` and `ISegmentAspect` data providers.
=> Return Table Column's Data Type (e.g., STRING, NUMBER, TIMESTAMP, etc.)

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/TableColumnHeader.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/TreeModelWrapper.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TreeColumnHeaderSerializer.java
Cherry-pick from master branch #84:
When requesting the table columns, the server will now return the type of each column. The types are derived from DataType enum, such as STRING, NUMBER, TIMESTAMP, DURATION, etc.
[Added] Accessing data type of table columns (i.e., headers)
=> server: Return table column data type

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java
The Trace Compass mainline PR below added a new trace properties to which has to be accounted for in the REST server tests:
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/155
=> server: Fix tests failing due to new trace properties added in TC

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ExperimentManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/TraceManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Experiment.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceManagerService.java
A separate trace instance was created to provide metadata info when a trace is queried. This commit removed the creation of that separate instance and open provide metadata info when the experiment is created.
=> [server] Stop creating a separate trace instance when posting a trace

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ExperimentManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/TraceManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Experiment.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceManagerService.java
A separate trace instance was created to provide metadata info when a trace is queried. This commit removed the creation of that separate instance and open provide metadata info when the experiment is created.
------------------------
Note: Cherry-pick from 2021-06 branch.
=> [server] Stop creating separate trace instances when posting a traces

tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/objects/Ros2ObjectsStateProvider.java
This PR is related to (and is needed after) https://github.com/ros2/ros2_tracing/pull/138.
ROS 2 publishers and subscriptions have unique IDs called GIDs (global IDs), which is part of the ROS 2 middleware interface (`rmw`). Their values are based on the corresponding objects in the underlying middleware, usually the GUID (globally unique ID) of the DDS data writer and data reader.
Historically, the ROS 2 (`rmw`) GID was a 24-byte array, while the DDS GUIDs are usually 16-byte arrays, at least for the ["main" DDS implementations](https://docs.ros.org/en/rolling/Installation/DDS-Implementations.html) (Fast DDS, Cyclone DDS, Connext DDS). Tthe `rmw` GID was then just the DDS GUID plus some 8-byte (zero) padding.
Since https://github.com/ros2/rmw/pull/345, the `rmw` GID size has been reduced …
=> ros2: fix size of publisher/subscription GIDs

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/META-INF/MANIFEST.MF, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/build.properties, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/plugin.xml, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/schema/custom-execution-analysis.json, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/TmfConfigurationSourceTypeStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/config/TestSchemaConfigurationSource.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ConfigurationSourceType.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TmfConfigurationSourceTypeSerializer.java
Support for [json-schema](https://json-schema.org/) in configuration source type:
- server: Serialize TmfConfigurationSourceType schema as string
- server: add test for TmfConfigurationSourceType with schema as string
- swagger: Document schema in TmfConfigurationSourceType
Requires https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/141
See also
- https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1108
- https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/103
=> Support for json-schema in configuration source type

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataProvider.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceServerOpenApiResource.java
server: Skeleton code for configuration service per data provider
[Added] Skeleton code for configuration service per data provider
Based on commits of PR #70. This one will be rebased once it's PR #70 merged.
=> server: Skeleton code for configuration service per data provider

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/DataProviderDescriptorSerializer.java
Requires https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/165.
=> server: serialize new parentId and configuration in DP descriptor

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/ConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ConfigurationManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
It uses the new `IDataProviderFactory.getAdapter()` interface to get `ITmfDataProviderConfigurator` implementation to create data providers. It passes an `ITmfConfiguration` instance with default TSP parameters (name, description, typeId) and the custom parameters in a JSON converted `Map<String, Object>` on to the configurator which the implementer of `ITmfDataProviderConfigurator` needs to apply.
It depends on 
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/154
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/167
~~This PR includes changes of PR #71 and its dependent pull requests, and will be rebased once dependent PRs are merged.~~
=> server: support for customizable data providers (outputs) via data provider factories

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/plugin.xml, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/DataProviderDescriptorStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/TestDataProviderFactory.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/config/TestSchemaConfigurationSource.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java
=> server: Add unit tests for configurable data providers

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ConfigurationManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Configuration.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/ConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/OutputConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ConfigurationManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
- Update documentation of Configuration and ConfigurationQueryParameters. 
Add name and description ConfigurationQueryParameters used for global configuration.
- Add configuration service per output (data provider)
This addition enables clients to create derived data providers from an existing data provider. This change also includes updates the "DataProvider" descriptor to include optional parent ID and configuration object to be included in derived data providers.
=> Swagger updates for global and output configuration

callstack/org.eclipse.tracecompass.incubator.callstack.core.tests/plugin.xml, callstack/org.eclipse.tracecompass.incubator.callstack.core/plugin.xml
The extension was not removed in the previous patch which creates an error when launching Trace Compass. This commit removes the extension from the plugin.xml.
Bernd Hufmann <bernd.hufmann@ericsson.com>
=> callstack: remove xml extension

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
- server: Return derived data provider descriptor when deleting it.
Update swagger description for deletion and method name.
- swagger: Fix response description for successful DP creation.
Update also method name.
=> Return deleted data provider descriptor and related swagger doc updates

analyses/org.eclipse.tracecompass.incubator.inandout.core/build.properties, analyses/org.eclipse.tracecompass.incubator.inandout.core/plugin.xml, analyses/org.eclipse.tracecompass.incubator.inandout.core/schema/in-and-out-analysis.json, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutAnalysisModule.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/SegmentSpecifierConfiguration.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
**Update (Oct 28, 0204):**
All the PRs below as well as relevant Trace Compass mainline are merged. This PR only has the changes of the InAndOut implementation left.
-------
This PR includes the TSP updates and concrete implementation for customizable analysis. The InAndOutAnalysis has been updated for that. This PR combines multiple commits, where some of them are available as separate PRs. It requires the commits of the following Trace Comapss mainline PR:
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/164
This PR combines the following commits/PRs:
- #66
- swagger: Document schema in TmfConfigurationSourceType
- server: Serialize TmfConfigurationSourceType schema json object
- #70 
- #71  
- #80
- InAndOutAnalysis with data provider factory and json string …
=> Custom analysis API and InAndOut Implementation

analyses/org.eclipse.tracecompass.incubator.inandout.core/schema/in-and-out-analysis.json
The name and description are default parameters for configurations and don't need to be part of the schema for the custom parameters of InAndOut analyses.
This PR is a fix-up to #88.
=> Remove name/description from InAndOut configuration schema

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/OutputConfigurationQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
In the OutputConfigurationQueryParameter the configuration source type id was called typeId and it creates a Configuration object where the same field is called sourceTypeId for the same field. When serializing the Configuration in the derived DataProviderDescriptor over TSP the field is called sourceTypeId and this is not consistent. The returned Configuration should have the exact field names that are used when creating the data provider and the respective configuration.
The Configuration is already API while OutputConfigurationQueryParameter is not, and it's better to change the name there.
=> Align OutputConfigurationQueryParameter/Configuration for sourceTypeId

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java
The bookmarks file can be used to store and retrieve markers associated with an experiment using platform APIs.
It can later be obtained for an opened experiment with: TmfTraceManager.getInstance().getTraceEditorFile(experiment)
=> server: Create bookmarks file for experiments

skeleton/scripts/update_version.sh, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/META-INF/MANIFEST.MF, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/IdentifierService.java
- Update script to match the rest.core version to the release version
- Match rest.core plug-in version with release version
- Fix version display provided by IdentifierService
Note: The rest.core plug-in version is retrieved to show in the identifier service. This is the only way to retrieve the version programmatically and hence the plug-in version and release version has to match.
fixes #121
=> Fix trace server version and display

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/BookmarkManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/BookmarkModelStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/webapp/TestWebApplication.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Bookmark.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/BookmarkQueryParameters.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/Bookmark.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/BookmarkManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/QueryParametersUtil.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceServerOpenApiResource.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/WebApplication.java
Using bookmarks, user can save custom data points where each corresponds to a specific time range. Each bookmark contains "name", "start", "end", and an optional "payload".
The following endpoints are introduced:
- [GET] Get all the bookmarks of an experiment
- [GET] Get a specific bookmark for an experiment
- [POST] Create a new bookmark for an experiment
- [PUT] Update an old bookmark of an experiment
- [DELETE] Delete a bookmark of an experiment
[Added] Corresponding endpoints for bookmarks in the trace server
=> server: Add bookmarks endpoint support

tracetypes/org.eclipse.tracecompass.incubator.uftrace.core/META-INF/MANIFEST.MF, tracetypes/org.eclipse.tracecompass.incubator.uftrace.core/src/org/eclipse/tracecompass/incubator/internal/uftrace/core/trace/Uftrace.java
Use CDT's cppFilt to demange c++ names if available.
=> uftrace: demangle c++ names

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
Trace Compass 10.2.0
Requires https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/194 to be merged and Trace Compass nightly update site build with it. 
=> releng: Upgrade target to dependencies of 2024-12 (Eclipse 4.34) release

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/META-INF/MANIFEST.MF
With this the interface ApplicationSupplier that the class org.glassfish.jersey.server.ResourceConfig implements can be resolved when running in the Eclipse development environment.
=> Add import package org.glassfish.jersey to rest.core.tests

tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/Activator.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/Ros2ObjectTimeGraphEntryModel.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/Ros2ObjectTimeGraphEntryModelType.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/messages/Ros2MessagesDataProvider.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/messages/Ros2MessagesStateProvider.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/messages/Ros2MessagesUtil.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/objects/Ros2ObjectsStateProvider.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/analysis/objects/Ros2ObjectsUtil.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/messages/Ros2MessageTransportInstance.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/messages/Ros2Request.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/messages/Ros2Response.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/objects/Ros2CallbackType.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/objects/Ros2ClientObject.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/model/objects/Ros2ServiceObject.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/trace/layout/IRos2EventLayout.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.core/src/org/eclipse/tracecompass/incubator/internal/ros2/core/trace/layout/Ros2RollingEventLayout.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.ui/src/org/eclipse/tracecompass/incubator/internal/ros2/ui/views/Ros2ObjectTreeLabelProvider.java, tracetypes/org.eclipse.tracecompass.incubator.ros2.ui/src/org/eclipse/tracecompass/incubator/internal/ros2/ui/views/messages/Ros2MessagesPresentationProvider.java
This adds support for the new client/service (i.e., RPC) instrumentation in ROS 2, see https://github.com/ros2/ros2_tracing/pull/145.
1. In the objects analysis, create client and service objects
2. In the messages analysis, create the following instances:
1. Request publication
2. Request take and callback
3. Response publication
4. Response take
5. Message transport for requests and responses
3. In the messages dataprovider, display the above instances
There is one limitation. Normal message publications and message takes have instrumentation that provides a "start time." For example, for message publications, the `ros2:rclcpp_publish` tracepoint is the start and the `ros2:rmw_publish` tracepoint is the end of a message publication. This allows us to attribute a duration to the …
=> ros2: support client/service instrumentation

ISSUE_TEMPLATE/bug_report.md, ISSUE_TEMPLATE/feature_request.md, ISSUE_TEMPLATE/question.md, PULL_REQUEST_TEMPLATE.md
This PR adds an issue and PR template in this repo, heavily inspired from those of the Eclipse CDT Cloud's theia-trace-extension project.
=> Add basic issue and pull-request templates

trace-server/README.md
This PR updates the trace server README link to the Jetty SSL setup documentation.
The existing link \[1\], to the Jetty documentation for the SSL setup, no longer resolves to the correct page, instead leading to a root documentation page on jetty.org, where one needs to pick the Jetty version to get to the documentation, and then search for the relevant SSL-related page.
Under there, I found what seems to be the relevant link for SSL documentation [2], for Jetty version 12 (latest as of now).
\[1\]: https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html
\[2\]: https://jetty.org/docs/jetty/12/operations-guide/keystore/index.html
N/A
N/A
=> [trace server] update link to Jetty SSL setup doc

analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/src/org/eclipse/tracecompass/incubator/inandout/core/tests/analysis/InAndOutDataProviderFactoryTest.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/DataProviderDescriptorSerializer.java
- trace-server: serialize IDataProviderCapabilities in descriptors
- Set Capabilities in relevant descriptors of InAndOutDataProviderFactory
Requires https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/198 to be integrated.
see also https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1158
=> Add support for data provider capabilities in server and InAndOut analysis

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataProvider.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputCapabilities.java
This PR adds the DataProviderCapabilities API to the swagger documentation. 
See ADR: https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1158
Run trace-server and create the API documentation as described here https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api.
N/A
=> swagger: Add DataProviderCapabilities to swagger documentation

.github/workflows/ci.yml
GitHub Actions deprecated v3 of actions/upload-artifact and actions/download-artifact. This PR upgrades github actions to v4 to ensure compatibility.
=> releng: upgrade github actions to v4 in the ci workflow

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-e4.34.target, common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target, pom.xml, rcp/org.eclipse.tracecompass.incubator.rcp.product/tracing.incubator.product, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
Update target files to include [JustJ JREs]( https://eclipse.dev/justj/) with respective version for that release. Use latest available JRE version for respective major version.
This will make it easier for end-users to use Trace Compass because Java doesn't need to be installed separately and it will include the correct, required version.
Notes:
- The stripped version of the JRE is used with debug information stripped and excluding the src.jar with sources used only for debugging. This minimizes the size of the JRE package because it's less than 1/2 the size of the corresponding full version. If you'd like to debug the RCP (e.g. using remote debugging), use a separated JVM as described below.
- To run the RCP with a different JVM (e.g. installed on user's laptop), open the …
=> releng: Bundle java runtime in Trace Compass RCP and Trace Server RCP

analyses/org.eclipse.tracecompass.incubator.executioncomparison.core/META-INF/MANIFEST.MF, analyses/org.eclipse.tracecompass.incubator.executioncomparison.core/src/org/eclipse/tracecompass/incubator/internal/executioncomparison/core/DifferentialSeqCallGraphAnalysis.java, analyses/org.eclipse.tracecompass.incubator.executioncomparison.ui/META-INF/MANIFEST.MF, analyses/org.eclipse.tracecompass.incubator.executioncomparison.ui/src/org/eclipse/tracecompass/incubator/internal/executioncomparison/ui/DifferentialFlameGraphView.java, analyses/org.eclipse.tracecompass.incubator.executioncomparison.ui/src/org/eclipse/tracecompass/incubator/internal/executioncomparison/ui/ExecutionComparisonView.java, analyses/org.eclipse.tracecompass.incubator.kernel.core/META-INF/MANIFEST.MF, analyses/org.eclipse.tracecompass.incubator.kernel.core/src/org/eclipse/tracecompass/incubator/internal/kernel/core/io/IoAccessDataProvider.java, analyses/org.eclipse.tracecompass.incubator.tmf.ui.multiview.ui/META-INF/MANIFEST.MF, analyses/org.eclipse.tracecompass.incubator.tmf.ui.multiview.ui/src/org/eclipse/tracecompass/incubator/internal/tmf/ui/multiview/ui/view/timegraph/AbstractTimeGraphMultiViewer.java, callstack/org.eclipse.tracecompass.incubator.callstack.core/META-INF/MANIFEST.MF, callstack/org.eclipse.tracecompass.incubator.callstack.core/src/org/eclipse/tracecompass/incubator/internal/callstack/core/flamegraph/FlameGraphDataProvider.java, callstack/org.eclipse.tracecompass.incubator.callstack.core/src/org/eclipse/tracecompass/incubator/internal/callstack/core/instrumented/provider/FlameChartDataProvider.java, callstack/org.eclipse.tracecompass.incubator.callstack.ui/META-INF/MANIFEST.MF, callstack/org.eclipse.tracecompass.incubator.callstack.ui/src/org/eclipse/tracecompass/incubator/internal/callstack/ui/flamegraph/FlameGraphView.java, common/org.eclipse.tracecompass.incubator.releng-site/category.xml, common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-e4.34.target, common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target, rcp/org.eclipse.tracecompass.incubator.rcp/feature.xml, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/META-INF/MANIFEST.MF, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TimeGraphArrowSerializer.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TimeGraphRowModelSerializer.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/legacy/traceserver.product, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
Replace all use of TraceCompassLogUtils with LogUtils from the trace-event-logger library.
Update all targets to include the trace-event-logger jar from Maven.
Add trace-event-logger plug-in to RCP feature and releng-site.
Add trace-event-logger plug-in to trace-server product.
Enable logging.
N/A
=> Use trace-event-logger lib

callstack/org.eclipse.tracecompass.incubator.analysis.core/plugin.xml, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/IReportDataProvider.java, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ImageReportDataProvider.java, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ReportsDataProviderFactory.java, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ReportsDataProviderRegistry.java, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/package-info.java
This PR introduces a new Reports Data Provider feature that enables users to:
- Define different types of reports (image, text, HTML)
- Create new configurations from report definitions
- Implement image report data provider as the initial consumer
This enhancement improves the flexibility of trace analysis by allowing users to generate and configure various report formats.
Manual testing via trace-server:
1. Start the trace-server
2. Access the configuration interface
3. Create a new configuration using the Reports Data Provider:
- Follow the standard configuration creation workflow
- Select and configure the desired report type
- Verify the configuration is saved correctly
- Validate that an image report can be generated
Note: Unit tests will be added in upcoming commits.
Future work:
- …
=> Configurable reports data provider

analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/src/org/eclipse/tracecompass/incubator/inandout/core/tests/analysis/InAndOutDataProviderFactoryTest.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java
Make fTmfConfigurationTable simply private.
This avoids that multiple instances of the same factory class can share the table.
Unit test updated accordingly.
Make fTmfConfigurationTable simply private, and then run the test as is on master. It will fail since a different instance of InAndOutDataProviderFactory is returned.
None
=> inandout: do not share configuration table

trace-server/org.eclipse.tracecompass.incubator.trace.server.product/legacy-e4.34/traceserver.product
Create legacy-e4.34/traceserver.product
Remove legacy/traceserver.product
To build for 4.34 target:
cp trace-server/org.eclipse.tracecompass.incubator.trace.server.product/legacy-e4.34/traceserver.product trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
mvn clean install -DskipTests=true -Dtarget-platform=tracecompass-incubator-e4.34 -Djdk.version=17 -Djdk.release=17
N/A
=> releng: Add legacy-e4.34/traceserver.product and remove obsolete legacy

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
As reports data provider is not yet supported properly in the front-end products (e.g., Eclipse UI, vscode/theia trace extension, etc.), we hide it temporarily, and once ready, we will unhide it.
When opening an experiment, fetch the outputs for it. In the fetched outputs list, the reports factory data provider should not be present. 
This data provider should be enabled once the front-end consumers support showing its outputs (e.g., containers/folders with different types of reports, such as images).
=> server: Hide reports factory data provider

tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkLogicalCoreAnalysisModule.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkLogicalCoreEventHandler.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkLogicalCoreEventLayout.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkLogicalCoreStateProvider.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/DpdkServiceEventHandler.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/LogicalCore.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/Messages.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/lcore/analysis/messages.properties
This commit fixes the following issues in the LCore analysis:
1. The lcore role "ROLE_SERVICE" was never assigned.
2. Certain lcore roles and statuses were not displayed because Enum values were
not converted to strings before saving them to the state system.
These fixes ensure proper role and status assignment alongside visibility in the UI. The following screenshots are for the LCore view showing:
- Three services running on two "RTE" LCores (with one idle LCore)
- Five services running on three "SERVICE" LCores (with two idle LCores).
=> dpdk: fix lcore role and status inconsistency

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderConfigurationServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
Validate parent descriptor when creating derived data provider.
This can prevent creating derived providers from hidden data providers.
With https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/243, configure the trace-server to hide a data provider configurator.
For example in ~/.tracecompass-webapp/.metadata/.plugins/org.eclipse.tracecompass.tmf.core/dataprovider.ini, add line:
hide:org.eclipse.tracecompass.incubator.inandout.core.analysis.inAndOutdataProviderFactory:*
Then try to create a derived data provider. For example using tsp-python-client:
./tsp_cli_client --create-output org.eclipse.tracecompass.incubator.inandout.core.analysis.inAndOutdataProviderFactory --uuid _uuid_ --json-file _jsonfile_
It should fail with 404 error code (Data provider doesn't exist).
N/A
=> server: Validate parent descriptor when creating derived data provider

analyses/org.eclipse.tracecompass.incubator.inandout.core.tests/src/org/eclipse/tracecompass/incubator/inandout/core/tests/analysis/InAndOutDataProviderFactoryTest.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutAnalysisModule.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java
When a configuration is applied, use the CONFIG_SEPARATOR '+' before the configId in the analysisId and outputId.
Create derived output from the factory and examine the analysisId and outputId.
N/A
=> inandout: Use config separator in analysis id and output id

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
Remove any instances of derived data providers and sub-data providers created with InAndAnalysis. 
fixes #178 
Requires the following Trace Compass PRs:
- https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/254
- https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/256
- https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/257
1. Create custom InAndOut using tsp-python-client
2. Open InAndOut call stack view from vscode-trace-extension
3. Delete custom InAndOut using tsp-python-client
4. Re-create same custom InAndOut as in 1)
5. Open InAndOut call stack view from vscode-trace-extension
6. The view is not empty 
Note: The same issue exists for the 3 other derived views and it is fixed with this PR.
Signed-off-by: Bernd Hufmann …
=> Remove customized data providers from manager

analyses/org.eclipse.tracecompass.incubator.inandout.core/schema/in-and-out-analysis.json
Remove required name in schema. The name is required by TSP protocol but is not part of the schema's
properties object.
The 'required' attribute should be outside the properties object.
Validate a JSON configuration without name field inside properties/parameters object.
N/A
=> inandout: Fix errors in JSON schema

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeQueryParameters.java
Replace requested_times with requested_timerange. This aligns with the description of the endpoints that use this parameter.
Generate TSP documentation. Look for the definition of parameters in the timegraph tree, XY tree and data tree endpoints.
N/A
=> swagger: Use requested_timerange in TreeQueryParameters

analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderConfigurator.java, analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderFactory.java
Move configurator implementation in own class. This makes the factory implementation leaner and separates the configurator implementation in an own class.
Create InAndOut configuration using the python client.
N/A
=> inandout: Move configurator implementation in own class

callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ImageReportDataProvider.java, callstack/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ReportsDataProviderFactory.java
Considering potential security issues, multiple logging statements have been introduced in this commit in the configurable reports data provider classes, enabling comprehensive monitoring of significant actions taken by the users. The logging implementation tracks key operations such as configuration creation, removal, as well as file system interactions and trace management activities. 
The stored logs for the `org.eclipse.tracecompass.incubator.analysis.core` bundle may be analyzed to verify the presence of logs of the two `ReportsDataProviderFactory` and `ImageReportDataProvider` classes.
In case of more requiring more detail analysis, further logging statements may be introduced.
=> Add logging to configurable reports data providers

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/RequestResponseLogger.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/WebApplication.java
With respect to the potential security issues, this commit tends to provide the required infrastructure for logging the incoming requests and outgoing responses that are handled by the trace server. We use the `LogUtils.traceInstant()` class to capture various information (e.g., path, IP, method, etc.) for each request/response.
* Request's unique ID
* HTTP method, path, query parameters
* Client IP address (including support for proxy headers)
* Headers and (truncated) body content for applicable methods
* Request's unique ID (from the original request)
* HTTP status code, content type, content length
* Total request processing duration
The trace server logging should be enabled (i.e., by running it with proper logging arguments). From that point, if the permission for the `Level.INFO` …
=> server: Add logging to the trace server endpoints

tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/META-INF/MANIFEST.MF, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/plugin.xml, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolAllocFreeRateDataProvider.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolAllocFreeRateDataProviderFactory.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolAnalysisModule.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolAttributes.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolEventHandler.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolEventLayout.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/DpdkMempoolStateProvider.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/Messages.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/messages.properties, tracetypes/org.eclipse.tracecompass.incubator.dpdk.core/src/org/eclipse/tracecompass/incubator/internal/dpdk/core/mempool/analysis/package-info.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/plugin.xml, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/src/org/eclipse/tracecompass/incubator/internal/dpdk/ui/mempool/alloc/free/rate/MempoolAllocFreeRateView.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/src/org/eclipse/tracecompass/incubator/internal/dpdk/ui/mempool/alloc/free/rate/MempoolAllocFreeRateViewer.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/src/org/eclipse/tracecompass/incubator/internal/dpdk/ui/mempool/alloc/free/rate/Messages.java, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/src/org/eclipse/tracecompass/incubator/internal/dpdk/ui/mempool/alloc/free/rate/messages.properties, tracetypes/org.eclipse.tracecompass.incubator.dpdk.ui/src/org/eclipse/tracecompass/incubator/internal/dpdk/ui/mempool/alloc/free/rate/package-info.java
This PR introduces a new analysis tool for DPDK traces focused on the Mempool library. By tracking how frequently DPDK threads allocate and free mempool objects, this analysis provides insights into application memory usage patterns. Since the Mempool library is used by the Mbuf library—which is leveraged by almost any DPDK application—this analysis can help identify memory-related bottlenecks and optimize mempools usage.
=> Dpdk: Add mempool object allocation/deallocation rate analysis

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/OutputElementStyle.java
Allow only certain data types for style values.
Fixes:
https://github.com/eclipse-cdt-cloud/trace-server-protocol/issues/102
[Generate openapi.yaml file](https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api) and verify changes fixes the reference bug in the TSP.
None
=> swagger: Fix type of style values for OutputElementStyle

analyses/org.eclipse.tracecompass.incubator.analysis.core/src/org/eclipse/tracecompass/incubator/analysis/core/reports/ReportsDataProviderFactory.java
This fixes the Exception below. The exception is caused because during shutdown the o.e.tc.incubator.analysis.core (for reports) Activator.stop() method is called before and the plug-in is removed from the static list of activators.
Remove the log statement to avoid this exception during shutdown.
java.lang.IllegalStateException
at org.eclipse.tracecompass.common.core.TraceCompassActivator.getInstance(TraceCompassActivator.java:86)
at org.eclipse.tracecompass.incubator.internal.analysis.core.Activator.getInstance(Activator.java:43)
at org.eclipse.tracecompass.incubator.analysis.core.reports.ReportsDataProviderFactory.dispose(ReportsDataProviderFactory.java:738)
at org.eclipse.tracecompass.tmf.core.dataprovider.DataProviderManager.dispose(DataProviderManager.java:117)
at …
=> reports: remove log in dispose() to avoid IllegalStateException

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/EntryModelStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/TgEntryModelStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/XyEntryModelStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeEntryModel.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/views/TreeModelWrapper.java
swagger: Add auto-expand level to TreeEntryModel
server: Add serialization of auto-expand level for tree models
tmf: Add auto-expand level in TmfTreeModel
Run updated unit tests.
Related incubator PR.
https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/196
Signed-off-by: Hriday Panchasara <hriday.panchasara@ericsson.com>
=> Add entry-tree parameter to collapse children

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TreeEntryModel.java
This parameter is optional but the description didn't clarify that and didn't mention the default value if it's omitted.
swagger: Clarify optional parameter autoExpandLevel
Verify correctness of description
TSP specification update
=> swagger: Clarify optional parameter autoExpandLevel

analyses/org.eclipse.tracecompass.incubator.inandout.core/src/org/eclipse/tracecompass/incubator/internal/inandout/core/analysis/InAndOutDataProviderConfigurator.java, common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
releng: Upgrade target to dependencies of 2025-06 (Eclipse 4.36) release
Build with target
N/A
=> releng: Upgrade target to dependencies of 2025-06 (Eclipse 4.36) release

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataProvider.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java
Added GANTT_CHART to DataProvider.ProviderType
=> Add GANTT_CHART to DataProvider.ProviderType

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/DataProviderConfigurationServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/ExperimentManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/TimeGraphDataProviderServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/services/TraceManagerServiceTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/ExperimentErrorResponseStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/TraceErrorResponseStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/utils/RestServerTest.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ErrorResponse.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Experiment.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/ExperimentErrorResponse.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/Trace.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TraceErrorResponse.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/BookmarkManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ConfigurationManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/EndpointConstants.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ErrorResponseImpl.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ErrorResponseUtil.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentErrorResponseImpl.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/ExperimentManagerService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/HealthService.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceErrorResponseImpl.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/TraceManagerService.java
When an error is created when processing a client request, return an ErrorResponse JSON object that includes
- title: short, human-readable description of the error
- detail: optional, human-readable explanation of the error
This standardizes the error response to common data structure. The field names and purpose are inspired by RFC 9457.
For 409 errors (trace or experiment) return extended ErrorResponse containing the conflicting trace or experiment respectively.
This commit also updates the swagger documentation in respect to the ErrorResponses accordingly.
Contributes to fix issue:
https://github.com/eclipse-cdt-cloud/trace-server-protocol/issues/122
- Verify using one example use case and see the returned data structure
- Thorough review to make sure that no case was missed.
Update …
=> server: Introduce ErrorResponse and use it in error responses

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/TimeGraphEntry.java
swagger: Fix supported types of TimeGraphEntry metadata values
fixes #129
Verify generated openapi.yaml (https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api)
TSP specification update
=> swagger: Fix supported types of TimeGraphEntry metadata values

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataTreeEntry.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataTreeEntryModel.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataTreeResponse.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/DataProviderService.java
swagger: Return DataTreeResponse instead of XYTreeResponse
The endpoint to fetch data tree swagger definition returned the XYTreeResponse and related data structures. This commit corrects the swagger definition for that.
Contributes to fixing of trace server protocol ticket: https://github.com/eclipse-cdt-cloud/trace-server-protocol/issues/128
Generate openapi.yaml https://github.com/eclipse-cdt-cloud/trace-server-protocol?tab=readme-ov-file#generate-the-api and verify changes.
Update TSP
=> swagger: Return DataTreeResponse instead of XYTreeResponse

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/model/DataProvider.java
Add TREE_GENERIC_XY enum that was previously missing.
Add the missing enum in swagger.
Run the server and visit http://localhost:8080/tsp/api/openapi.yaml and check that `TREE_GENERIC_XY` is avaiable.
Update in `trace-server-protocol`:
[Update in https://github.com/eclipse-cdt-cloud/trace-server-protocol.
](https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/137)
- [Y] As an author, I have thoroughly tested my changes and carefully followed the instructions in this template
=> swagger: add TREE_GENERIC_XY enum

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
releng: fix org.glassfish.jersey.media;jersey-media-jaxb version 2.47. The trace server uses Jersey 2.47 and this dependency should match. Otherwise wrong version might be selected in development environment.
Successful setting updated target in Eclipse IDE and start trace server successfully. 
N/A
=> releng: fix org.glassfish.jersey.media;jersey-media-jaxb version 2.47

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target
releng: remove unused org.glassfish.jersey.media;jersey-media-jaxb. No XML data is used in the trace server and hence this library is not needed.
Build trace server locally and use it successfully with one of the TSP clients (e.g. vscode-trace-extension)
N/A
=> releng: remove unused org.glassfish.jersey.media

common/org.eclipse.tracecompass.incubator.target/tracecompass-incubator-master.target, rcp/org.eclipse.tracecompass.incubator.rcp/feature.xml, trace-server/org.eclipse.tracecompass.incubator.trace.server.product/traceserver.product
releng: Upgrade target to dependencies of 2025-09 (Eclipse 4.37) release
Build with latest target
N/A
=> releng: Upgrade target to dependencies of 2025-09 (Eclipse 4.37) release

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/services/QueryParametersUtil.java
server: Allow lower case strings for time graph tooltip's element type.
The TSP specifies that the element type should be upper case (due to enum). This code change will convert the input value to lower case before comparing the actual string. This will allow TSP clients to slowly update to the TSP compliant values.
fixes #240
Follow steps in #240 and verify that test are successful.
=> server: Allow lower case strings for time graph tooltip's element type

trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.tests/src/org/eclipse/tracecompass/incubator/trace/server/jersey/rest/core/tests/stubs/ConfigParamDescriptorStub.java, trace-server/org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core/src/org/eclipse/tracecompass/incubator/internal/trace/server/jersey/rest/core/webapp/TmfConfigParamDescriptorSerializer.java
Serialize field name as `required` as specified in TSP instead of `isRequired`
fixes #246
Follow instructions in #246 to verify.
=> server: serialize field `required` as specified in TSP
